### ISSUE TITLE
In den Buildserver eintragen

### ISSUE THREAD

**Issue by patkan** [fau-fablab/ultraschallbad-einweisung#2]
Sobald ein sauber bauendes Dokument vorliegt, muss das in den Buildserver eingetragen werden.

**Comment by sedrubal** [comment]
der build auf dem buildserver schlägt fehl, weil `pdflatex` fehlt. Entweder muss man das installieren oder nachvollziehen, warum man für die Ultraschallbad Einweisung `pdflatex` braucht und für die anderen nicht...

**Comment by mgmax** [comment]
tut wieder, texlive-full war noch ned installiert. upsi.
